name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld qemu-system-riscv32 curl

      - name: Install OpenSBI
        run: |
          curl -LO https://github.com/qemu/qemu/raw/v8.0.4/pc-bios/opensbi-riscv32-generic-fw_dynamic.bin
          echo "QEMU_BIOS_PATH=$(pwd)/opensbi-riscv32-generic-fw_dynamic.bin" >> $GITHUB_ENV

      - name: Build
        run: ./build.sh

  codeQL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp
      - name: Build (for CodeQL database)
        run: |
          # give a build step that CodeQL can observe; you can use your build.sh
          ./build.sh
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

